version: '3'

services:
    db:
        image: mysql:8.0
        container_name: feed-mysql-dev
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - "./db/data:/var/lib/mysql"
            - "./db/initdb.d:/docker-entrypoint-initdb.d"
            - "./data:/data"
        ports:
            - "3308:3306"
        environment:
            TZ: Asia/Seoul
            MYSQL_DATABASE: feed
            MYSQL_PORT: 3306
            MYSQL_ROOT_PASSWORD: pwd1234!
